-- EXERCISE 1
CREATE DATABASE ONLINECONSULTATION;
CREATE TABLE DOCTOR(
ID INT PRIMARY KEY NOT NULL,NAME_ VARCHAR(30) NOT NULL,SPECIALIZATION VARCHAR(30) NOT NULL,CONTACT_NUM INT NOT NULL);
-- INSERT INTO DOCTOR VALUES(200913,'DR. KARTHIK','CARDIOLOGIST'),
-- (200914,'DR.VYSHNAVI','DERMATALOGY'),
-- (200915,'DR.USHA RANI','NEUROLOGY');
DROP TABLE appointments;
CREATE TABLE APPOINTMENTS(APPOINTMENT_ID INT PRIMARY KEY NOT NULL,
DOCTOR VARCHAR(30) NOT NULL,PATIENT VARCHAR(30) NOT NULL,DATE_ DATE NOT NULL,PATIENT_CONTACT INT NOT NULL);

CREATE TABLE PATIENT(
PATIENT_NAME VARCHAR(30) NOT NULL,AGE INT NOT NULL,GENDER VARCHAR(2) NOT NULL,
DISEASE VARCHAR(30) NOT NULL);

CREATE TABLE REVIEWS(DOCTOR_NAME VARCHAR(30) NOT NULL,
PATIENT_NAME VARCHAR(30) NOT NULL,REVIEW_RATE INT );
-- EXCERCISE 2 
CREATE TABLE CONTACT(
Id INT PRIMARY KEY NOT NULL,Email VARCHAR(30) NOT NULL,
fname VARCHAR(30) NOT NULL,Iname VARCHAR(30) NOT NULL,
company VARCHAR(30) NOT NULL,Active_flag INT NOT NULL,opt_out INT NOT NULL);

INSERT INTO CONTACT VALUES(123,'a@a.com','Kian','Seth','ABC',1,1),
(133,'b@b.com','Neha','Seth','ABC',1,0),
(234,'c@c.com','Puru','Malik','CDF',0,0),
(342,'d@d.com','Sid','Maan','TEG',1,0);
SELECT * FROM CONTACT;
SELECT * FROM CONTACT WHERE Active_flag = 1;
DELETE  FROM CONTACT WHERE opt_out = 1;
DELETE FROM CONTACT WHERE company = 'ABC';
SELECT * FROM CONTACT;
INSERT INTO CONTACT VALUES(658,'mili@gmail.com','___','mili','DGH',1,1);
SELECT DISTINCT COMPANY FROM CONTACT;
UPDATE CONTACT SET Iname = 'niti' WHERE Iname = 'mili';

-- EXERCISE 3
CREATE TABLE CUSTOMER(
customer_id INT PRIMARY KEY NOT NULL,cust_name VARCHAR(30) NOT NULL,city VARCHAR(30) NOT NULL,
GRADE INT ,salesman_id INT NOT NULL);

INSERT INTO CUSTOMER VALUES('3002','Nick Rimando','New york',100,5001),('3007','Braf Davis','New york',200,5001),
('3005','Graham Zusi','California',200,5002),
('3008','Julian Green','London',300,5002),
('3004','Fabian Johnson','Paris',300,5006),
('3009','Geoff Cameron','Berlin',100,5003),
('3003','Jozy Altidor','Moscow',200,5007),('3001','Brad Guza','London',null,5001);

CREATE TABLE SALESMAN (
salesman_id INT NOT NULL,name_ VARCHAR(30) NOT NULL,
city VARCHAR(30) NOT NULL,commission FLOAT NOT NULL);
drop table salesman;
drop table customer;
INSERT INTO SALESMAN VALUES(5001,'James Hoog','New york',0.15),(5002,'Nail Knite','Paris',0.13),
(5005,'Pit Alex','London',0.11),(5006,'Mc Lyon','Paris',0.14),
(5007,'Paul Adam','Rome',0.13),(5003,'Lauson Hen','San Jose',0.12);
SELECT * FROM SALESMAN;
SELECT * FROM CUSTOMER;

SELECT CUSTOMER.customer_id,CUSTOMER.city,CUSTOMER.grade,SALESMAN.name_,SALESMAN.city FROM CUSTOMER
RIGHT JOIN CUSTOMER ON CUSTOMER.salesman_id= SALESMAN.salesman_id WHERE CUSTOMER.GRADE < 100 ORDER BY CUSTOMER_ID;
